// <auto-generated />
namespace Budgetis_V0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MiseAjourTacheDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MiseAjourTacheDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201706251736592_MiseAjourTacheDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
